Use employees;
SELECT first_name, last_name FROM employees;
SELECT * FROM employees;
SELECT dept_no FROM departments; 
SELECT * FROM departments;
SELECT * FROM employees WHERE first_name = 'Denis';
SELECT * FROM employees WHERE first_name = 'Elvis';
SELECT * FROM employees WHERE first_name = 'Denis' AND gender = 'M';
SELECT * FROM employees WHERE first_name = 'Kellie' AND gender = 'F';
SELECT * FROM employees WHERE first_name = 'Denis' OR first_name = 'Elvis';
SELECT * FROM employees WHERE first_name = 'Kellie' OR first_name = 'Aruna';
SELECT * FROM employees WHERE last_name = 'Denis' AND (gender = 'M' OR gender = 'F');
SELECT * FROM employees WHERE gender = 'F' AND (first_name = 'Kellie' OR first_name = 'Aruna');
SELECT * FROM employees WHERE first_name = 'Cathie' OR first_name = 'Mark' OR first_name = 'Nathan';
/* to apply more than one conditions use in operator. IN operator faster than OR operator */
SELECT * FROM employees WHERE first_name IN ('Cathie', 'Mark' , 'Nathan');
SELECT * FROM employees WHERE first_name NOT IN ('Cathie', 'Mark' , 'Nathan');
SELECT * FROM employees WHERE first_name IN ('Denis', 'Elvis');
SELECT * FROM employees WHERE first_name IN ('John', 'Mark', 'Jacob');
SELECT * FROM employees WHERE first_name LIKE ('%Mar%');
SELECT * FROM employees WHERE first_name LIKE ('Mar%');
SELECT * FROM employees WHERE hire_date LIKE ('%2000%');
SELECT * FROM employees WHERE emp_no LIKE ('1000_');
SELECT * FROM employees WHERE first_name LIKE ('%jack%');
SELECT * FROM employees WHERE first_name NOT LIKE ('%jack%');
SELECT * FROM employees WHERE hire_date BETWEEN '1990-01-01' AND '2000-01-01';
SELECT * FROM employees WHERE hire_date NOT BETWEEN '1990-01-01' AND '2000-01-01';
SELECT * FROM salaries WHERE salary BETWEEN '66000' AND '70000';
SELECT * FROM employees WHERE emp_no NOT BETWEEN '10004' AND '10012';
SELECT * FROM departments WHERE dept_no BETWEEN 'd003' AND 'd006';
SELECT * FROM employees WHERE first_name IS NOT NULL;
SELECT dept_name FROM departments WHERE dept_no IS NOT NULL;
SELECT * FROM employees WHERE first_name <> 'Mark';
SELECT * FROM employees WHERE hire_date > '2000-01-01';
SELECT * FROM employees WHERE hire_date >= '2000-01-01';
SELECT * FROM employees WHERE hire_date < '1985-02-01';
SELECT * FROM employees WHERE hire_date <= '1985-02-01';
SELECT * FROM employees WHERE gender = 'F' AND hire_date > '2000-01-01';
SELECT * FROM salaries WHERE salary > '150000';
